const BLACK = "#000000";
const LIGHT_BLACK = "#43463E";
const WHITE = "#FFFFFF";
const LIGHT_GREEN = "#94C54E";
const DARK_GREEN = "#7F9B57";
const BRIGHT_GREEN = "#A3F037";

export { BLACK, LIGHT_BLACK, BRIGHT_GREEN, LIGHT_GREEN, DARK_GREEN, WHITE };
